### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by kaesetoast** [AtomLinter/linter-jshint#115]
Since the last update I keep getting the following Error when opening a .js file:

```
Unexpected end of input
SyntaxError: Unexpected end of input
  at Object.parse (native)
  at /home/philipp/.atom/packages/linter-jshint/lib/main.coffee:22:23
```

Linting does not work either anymore.

**Comment by steelbrain** [comment]
From the other thread: I am unable to repro this, can someone do `coffeelint ~/.atom/packages/linter-jshint/lib` and post the results?

**Comment by iam4x** [comment]
@steelbrain It's the `JSON.parse` fails

**Comment by kaesetoast** [comment]
Woah, sorry.. Didn't notice that I was posting in the closed thread.. So here it is again for consistency :-)

```
➜  ay.dev master ✗ coffeelint ~/.atom/packages/linter-jshint/lib
  ✗ /home/philipp/.atom/packages/linter-jshint/lib/main.coffee
     ✗ #9: Line exceeds maximum allowed length. Length is 88, max is 80.
     ✗ #20: Line exceeds maximum allowed length. Length is 95, max is 80.
     ✗ #21: Line exceeds maximum allowed length. Length is 83, max is 80.
     ✗ #22: Line exceeds maximum allowed length. Length is 91, max is 80.

✗ Lint! » 4 errors and 0 warnings in 1 file
```

**Comment by varemenos** [comment]
```
  ✗ /Users/adonisk/.atom/packages/linter-jshint/lib/main.coffee
     ✗ #9: Line exceeds maximum allowed length. Length is 88, max is 80.
     ✗ #20: Line exceeds maximum allowed length. Length is 95, max is 80.
     ✗ #21: Line exceeds maximum allowed length. Length is 83, max is 80.
     ✗ #22: Line exceeds maximum allowed length. Length is 91, max is 80.

✗ Lint! » 4 errors and 0 warnings in 1 file
```

**Comment by vdclouis** [comment]
If this helps:
```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/*/.atom/packages/linter-jshint/lib/main.coffee:28:25
```

**Comment by ketamin** [comment]
Hi, I made this line in main.coffee:
exePath = atom.config.get('jshintExecutablePath') or jshintPath
to:
exePath = jshintPath

and the error won't occure anymore.
In my settings, the path was blank.
Hope this helps fixing it in a better way than I did.

**Comment by jbkirby** [comment]
Same error here.

**Comment by adarhef** [comment]
Same error here. ketamin's solution didn't seem to work for me.

**Comment by steelbrain** [comment]
None of you have syntax errors reported via coffeelint, it's weird.

**Comment by steelbrain** [comment]
Just pushed a patch release, does it work for you?

**Comment by vdclouis** [comment]
nope, still getting this:
```
SyntaxError: Unexpected end of input
  at Object.parse (native)
  at /Users/louisvandecalseyde/.atom/packages/linter-jshint/lib/main.coffee:22:23
```

**Comment by agos** [comment]
patch not working for me as well

**Comment by mnort9** [comment]
+1 😟

**Comment by steelbrain** [comment]
I'll try something else then.
__Note:__ It's working 100% fine for me :stuck_out_tongue:

**Comment by iam4x** [comment]
Guys, are starting Atom with CLI or launcher? Try with CLI if not.

**Comment by steelbrain** [comment]
Does this patch work for anyone? 
https://github.com/AtomLinter/linter-jshint/commit/492771767e2fd69fb3eb24ad11b17cfe9c5eb818.patch

**Comment by Robert-W** [comment]
@iam4x Interesting, that actually works and seems to do fine, launching from the applications folder does not work but CLI is all good

**Comment by steelbrain** [comment]
Ahh! It was a json parsing issue, I think I know what to do now.

**Comment by ketamin** [comment]
With your latest changes, my console shows this:

```
Uncaught Error: write EPIPE
JSHint Result: 
```

**Comment by steelbrain** [comment]
That's a known bug on windows, working on the fix

**Comment by steelbrain** [comment]
Fixed by a patch release.

**Comment by Robert-W** [comment]
Uncaught Error: write EPIPE
/Users/Robert/.atom/packages/linter-jshint/lib/main.coffee:37 JSHint Result: 

Now seeing this as well with the latest (1.0.2), regardless of opening from CLI or launcher. Running on OSX 10.10.4.

However, the Unexpected End of Input error is gone and seems to be fixed.

**Comment by steelbrain** [comment]
Maybe related to https://github.com/AtomLinter/linter-jshint/issues/117

**Comment by kaesetoast** [comment]
The Linter works well for me if I open atom via CLI. When I open it via the menu launcher (working on linux), I still get the following error in the console:

```
Uncaught Error: write EPIPE
/home/philipp/.atom/packages/linter-jshint/lib/main.coffee:37 JSHint Result:
```

Thanks for the effort by the way. It's amazing to see an issue progress that fast. That's how OpenSource can be fun :-) :+1:

**Comment by varemenos** [comment]
I'm now getting:
```
Invalid result received from JSHint
```
In the error notification and the console indicates the following file and line:
```
/Users/akakoulidis/.atom/packages/linter-jshint/lib/main.coffee:37
```

**Comment by steelbrain** [comment]
What do you see in your console? that's the helpful part.

**Comment by varemenos** [comment]
Nothing, it just indicates this line:

```
JSHint Result: /Users/akakoulidis/.atom/packages/linter-jshint/lib/main.coffee:37
```

**Comment by kaesetoast** [comment]
![bildschirmfoto vom 2015-07-10 16 58 47](https://cloud.githubusercontent.com/assets/1102078/8621257/f4b5c1a2-2724-11e5-91fa-68df0aaac9f2.png)

**Comment by steelbrain** [comment]
@kaesetoast for your specific case, I suggest you try linting from CLI and see if it works

**Comment by vdclouis** [comment]
I have the exact some problem on osx

**Comment by Robert-W** [comment]
It seems to me that this is inside a try catch for<code>JSON.parse(output).result</code>, the console.log('JSHint Result:', output); is logging correctly but output seems to be null or undefined.
I dont think this is related to #117, this seems to be an error with the JSON.parse

**Comment by steelbrain** [comment]
@Robert-W for me it's
```
          try
            output = JSON.parse(output).result
          catch error
            atom.notifications.addError("Invalid Result recieved from JSHint", {detail: "Check your console for more info", dismissible: true})
            console.log('JSHint Result:', output)
            return []
```

**Comment by vdclouis** [comment]
when debugging:
https://cldup.com/-1qqwGzDUr.png

**Comment by steelbrain** [comment]
@vdclouis that's a JSON parse error. but the fact that output is null is interesting. what OS are you on?

**Comment by vdclouis** [comment]
osx 10.11

**Comment by steelbrain** [comment]
Does jshint report errors to stdout or stderr in OSX, 'cause in linux it loggs it's errors to stdout.

**Comment by Robert-W** [comment]
Seeing the same as @vdclouis, 
<pre><code>
return helpers.exec(exePath, parameters, {
  stdin: text
}).then(function(output) {
  var error;
</code></pre> 
In the callback output is actually empty string so calling JSON.parse on empty string seems to throw the error.

**Comment by steelbrain** [comment]
@Robert-W it seems like a jshint, or a stream issue to me.

**Comment by Robert-W** [comment]
Yup I think your right, Actually closed and restarted Atom from the CLI and now its fine, but launcher still has issue. This may need to be bubbled up to JSHint or atom-linter.

It looks like:
<code>helpers.exec(exePath, parameters, {stdin: text}).then (output)</code> is passing an empty string through to the resolve and helpers is directly from 
<code>require('atom-linter')</code>

**Comment by steelbrain** [comment]
Aaha! so it's an node bug! that `child_process.spawn` only respects `$PATH` when triggered from CLI on OSX.

**Comment by Robert-W** [comment]
same error from launcher still, cli is fine, checked <code>exePath</code>, <code>parameters</code>, and <code>text</code> variables and all have valid content before getting passed into <code>helpers.exec</code>.  Thanks for all the help by the way.  Also, running this in the console: 
<pre><code>
helpers.exec(exePath, parameters, { stdin: text}).then(function () {
  console.log(arguments);
});
</code></pre>

logs <code>[""]</code>.
The variables values look the same when running from cli and from launcher so I am starting to think there is an issue with that node bug in helpers.exec from atom-linter when opened from launcher,

**Comment by steelbrain** [comment]
`atom-linter` npm module doesn't really do anything by itself, it just organizes the info and feeds it to node's `child_process.spawn` :)

**Comment by Robert-W** [comment]
ahh ok, hmm.  All the variables passed in look the same when launched from launcher and cli, I did not run a comparison but just quickly glanced at them, but they both seemed fine.  Not sure then, thanks anyway, launching from CLI for now

**Comment by Robert-W** [comment]
may try to help debug more later after work if this is still active by then

**Comment by steelbrain** [comment]
Sure, just ping me in #linter of atom slack.

**Comment by Robert-W** [comment]
Cool, thanks again

**Comment by steelbrain** [comment]
Should continue to the discusison to https://github.com/AtomLinter/Linter/issues/726
